INSERT INTO Airports VALUES ('ATL', 'Hartsfield–Jackson Atlanta International Airport', 'Atlanta', 'Georgia', 'US', 1, 36676010);
INSERT INTO Airports VALUES ('DFW', 'Dallas/Fort Worth International Airport', 'Dallas', 'Texas', 'US', 2, 30005266);
INSERT INTO Airports VALUES ('DEN', 'Denver International Airport', 'Denver', 'Colorado', 'US', 3, 28645527);
INSERT INTO Airports VALUES ('ORD', "O'Hare International Airport", 'Chicago', 'Illinois', 'US', 4, 26350976);
INSERT INTO Airports VALUES ('LAX', 'Los Angeles International Airport', 'Los Angeles', 'California', 'US', 5, 23663410);
INSERT INTO Airports VALUES ('CLT', 'Charlotte Douglas International Airport', 'Charlotte', 'North Carolina', 'US', 6, 20900875);
INSERT INTO Airports VALUES ('MCO', 'Orlando International Airport', 'Orlando', 'Florida', 'US', 7, 19618838);
INSERT INTO Airports VALUES ('LAS', 'Harry Reid International Airport', 'Las Vegas', 'Nevada', 'US', 8, 19160342);
INSERT INTO Airports VALUES ('PHX', 'Phoenix Sky Harbor International Airport', 'Phoenix', 'Arizona', 'US', 9, 18940287);
INSERT INTO Airports VALUES ('MIA', 'Miami International Airport', 'Miami', 'Florida', 'US', 10, 17500096);
INSERT INTO Airports VALUES ('SEA', 'Seattle–Tacoma International Airport', 'Seattle', 'Washington', 'US', 11, 17430195);
INSERT INTO Airports VALUES ('IAH', 'George Bush Intercontinental Airport', 'Houston', 'Texas', 'US', 12, 16242821);
INSERT INTO Airports VALUES ('JFK', 'John F. Kennedy International Airport', 'New York City', 'New York', 'US', 13, 15273342);
INSERT INTO Airports VALUES ('EWR', 'Newark Liberty International Airport', 'Newark', 'New Jersey', 'US', 14, 14514049);
INSERT INTO Airports VALUES ('FLL', 'Fort Lauderdale–Hollywood International Airport', 'Fort Lauderdale', 'Florida', 'US', 15, 13598994);
INSERT INTO Airports VALUES ('MSP', 'Minneapolis–Saint Paul International Airport', 'Minneapolis', 'Minnesota', 'US', 16, 12211409);
INSERT INTO Airports VALUES ('SFO', 'San Francisco International Airport', 'San Francisco', 'California', 'US', 17, 11725347);
INSERT INTO Airports VALUES ('DTW', 'Detroit Metropolitan Airport', 'Detroit', 'Michigan', 'US', 18, 11517696);
INSERT INTO Airports VALUES ('BOS', 'Logan International Airport', 'Boston', 'Massachusetts', 'US', 19, 10909817);
INSERT INTO Airports VALUES ('SLC', 'Salt Lake City International Airport', 'Salt Lake City', 'Utah', 'US', 20, 10795906);
INSERT INTO Airports VALUES ('PHL', 'Philadelphia International Airport', 'Philadelphia', 'Pennsylvania', 'US', 21, 9809968);
INSERT INTO Airports VALUES ('BWI', 'Baltimore/Washington International Airport', 'Baltimore', 'Maryland', 'US', 22, 9253561);
INSERT INTO Airports VALUES ('TPA', 'Tampa International Airport', 'Tampa', 'Florida', 'US', 23, 8847197);
INSERT INTO Airports VALUES ('SAN', 'San Diego International Airport', 'San Diego', 'California', 'US', 24, 7836360);
INSERT INTO Airports VALUES ('LGA', 'LaGuardia Airport', 'New York City', 'New York', 'US', 25, 7827307);
INSERT INTO Airports VALUES ('MDW', 'Midway International Airport', 'Chicago', 'Illinois', 'US', 26, 7680617);
INSERT INTO Airports VALUES ('BNA', 'Nashville International Airport', 'Nashville', 'Tennessee', 'US', 27, 7594049);
INSERT INTO Airports VALUES ('IAD', 'Washington Dulles International Airport', 'Washington, D.C.', 'District of Columbia', 'US', 28, 7227875);

