/*!40101 SET NAMES utf8 */;
/*!40101 SET SQL_MODE=''*/;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`leboreddata` /*!40100 DEFAULT CHARACTER 
SET latin1 */;

USE `leboreddata`;

CREATE TABLE Airports (
    IATACode VARCHAR(255),
    Name VARCHAR(255),
    City VARCHAR(255),
    State VARCHAR(255),
    Country VARCHAR(255),
    PassengerRank2021 INT,
    PassengerServed2021 INT,
    PRIMARY KEY (IATACode)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE Airlines (
    Name VARCHAR(255),
    MainHub VARCHAR(255),
    IATACode VARCHAR(255),
    PRIMARY KEY (IATACode),
    FOREIGN KEY (MainHub) REFERENCES Airports(IATACode) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE Planes (
    Manufacturer VARCHAR(255),
    Model VARCHAR(255),
    NumInUSFleet INT,
    KgPKm REAL,
    MaxPassengers INT,
    PRIMARY KEY (Model)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE Passengers (
    Name VARCHAR(255),
    MainAirline VARCHAR(255),
    RewardsID VARCHAR(255),
    Age INT,
    Gender VARCHAR(255),
    Race VARCHAR(255),
    HomeAirport VARCHAR(255),
    PRIMARY KEY (RewardsID),
    FOREIGN KEY (MainAirline) REFERENCES Airlines(IATACode) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (HomeAirport) REFERENCES Airports(IATACode) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE Flights (
    IATACode VARCHAR(255),
    FlightNum VARCHAR(255),
    DepartFrom VARCHAR(255),
    Destination VARCHAR(255),
    Manufacturer VARCHAR(255),
    Model VARCHAR(255),
    TakeoffDate DATE,
    PRIMARY KEY (FlightNum),
    FOREIGN KEY (IATACode) REFERENCES Airlines(IATACode) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (DepartFrom) REFERENCES Airports(IATACode) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (Destination) REFERENCES Airports(IATACode) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (Model) REFERENCES Planes(Model) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE Tickets (
    TicketID VARCHAR(255),
    Airline VARCHAR(255),
    FlightNum VARCHAR(255),
    RewardsID VARCHAR(255),
    Price REAL,
    PRIMARY KEY (TicketID),
    FOREIGN KEY (Airline) REFERENCES Flights(IATACode) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (FlightNum) REFERENCES Flights(FlightNum) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (RewardsID) REFERENCES Passengers(RewardsID) ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;